version: '3.4'

services:
  drip-chip-api:
    image: dripchipapi
    build:
      context: .
      dockerfile: drip-chip-api/Dockerfile

  tests: 
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - drip-chip-api
    environment:
      SERVER_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5002/api
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа